### ISSUE TITLE
List user's groups

### ISSUE THREAD

**Issue by rodrigor** [richig-vienna/DokuWiki-ListUsergroup-Plugin#2]
Add a new variable "groups" to show the groups related to a user.

Example:
{{listusergroup>group=user;show=user,groups}}

Above definitions create a table with all members from group 'user'.
No table's CSS class is given.
Order for 'Show' is relevant (no header for the table):
  - 1st show 'login name'
  - 2nd shows a comma-separated list of the groups of the user.

**Comment by richig-vienna** [comment]
Added a new variable "groups" to show the groups related to a user.

**Comment by richig-vienna** [comment]
Added new variable "groups" and tested it sucessfully.
