### ISSUE TITLE
Listusergroup stopped working

### ISSUE THREAD

**Issue by Pazukulele** [richig-vienna/DokuWiki-ListUsergroup-Plugin#3]
I have been using groupmail successfully for quite a while. After installing listusergroup, however, groupmail has stopped working (SMTP testing is however functional). Moreover, in the user listings (both with listusergroup and groupusers), most user full names are not displayed; instead, I get incremental numbers starting with 0. Most of my user names consist of numbers; only those user names consisting of letters are correctly displayed.
Groupmail is not working even after deinstalling listusergroup. I am wondering what kind of incompatibility I may have run in, and particularly why user names are not displayed correctly.
I am using 2020-07-29 "Hogfather". SMTP is set up correctly and working. For the issue concerned, I am using listusergroup (reinstalled it today but still get notification that version 2020-11-27 is downloadable?!) and Group mailing system. I created a test group which contains the following data:

Benutzername,"Voller Name",E-Mail,Gruppen
primu,"Primus Murksus",primu@pau.info,test
secmu,"Secundus Murksus",secmu@pau.info,test
termu,"Tertius Murksus",termu@pau.info,test
2345678,"Musterfrau (Erika)",musterfrau@pau.info,test
123456789,"Quartus Murksus",quamu@pau.info,test
234567890,"Quintus Murkus",quimu@pau.info,test
345678901,"Sextus Murksus",sexmu@pau.info,test

In the following environment:

`<searchtable>`
`<sortable>`
`{{listusergroup>group=test;class=inline;show=header,user,fullname,email,groups;link=email}}`
`</sortable>`
`</searchtable>`

the data is displayed as:

Benutzername | Voller Name | E-Mail |  
primu | Primus Murksus | primu@pau.info | test
secmu | Secundus Murksus | secmu@pau.info | test
termu | Tertius Murksus | termu@pau.info | test
0 | Musterfrau (Erika) | musterfrau@pau.info | test
1 | Quartus Murksus | quamu@pau.info | test
2 | Quintus Murkus | quimu@pau.info | test
3 | Sextus Murksus | sexmu@pau.info | test

So while usernames with letters are represented correctly, usernames with numbers are not.

groupmail is configured as follows:

`{{groupmail>bccgroup=test|autofrom|sendlog=:playground:test:log}}`

**Comment by richig-vienna** [comment]
I was able to reproduce the issue visualizing "incremental numbers starting with 0. Most of my user names consist of numbers; only those user names consisting of letters are correctly displayed.".
Have to analyse it.

Update: FIXED

**Comment by Pazukulele** [comment]
Thank you! Problem is solved.
